import { describe, expect, it } from 'vitest';

import { emitWebsiteGeneratedModules } from '../src/content/pipeline/website/emitter';
import type { WebsiteCompiledContent } from '../src/content/pipeline/website/adapter';

const compiledContent: WebsiteCompiledContent = {
  pages: [
    {
      routeId: 'quickstart',
      summary: 'Start quickly.',
      bodyHtml: '<h1>Quickstart</h1>',
      sections: [{ heading: 'Quickstart', body: 'Start quickly.' }],
      links: [],
      sourceTrace: {
        markdownPath: 'src/content/copy/quickstart/index.md',
        manifestPath: 'src/content/quickstart.manifest.ts',
        contentHash: 'a'.repeat(64),
        headings: [{ id: 'quickstart', label: 'Quickstart', level: 1, line: 1, column: 1 }],
        links: [],
        images: [],
      },
    },
  ],
  routes: [],
  navigation: [],
  media: [],
};

describe('website generated TypeScript emitter', () => {
  it('emits deterministic modules with generated-file headers', () => {
    const first = emitWebsiteGeneratedModules(compiledContent);
    const second = emitWebsiteGeneratedModules(compiledContent);

    expect(first).toEqual(second);
    expect(first.pages).toContain('This file is generated by Commonloom. Do not edit.');
    expect(first.pages).toContain('satisfies readonly WebsiteGeneratedPage[]');
    expect(first.index).toContain("export * from './pages.generated';");
  });

  it('keeps JSON out of renderer inputs', () => {
    const modules = emitWebsiteGeneratedModules(compiledContent);

    expect(Object.keys(modules)).toEqual(['routes', 'pages', 'navigation', 'media', 'index']);
    expect(Object.values(modules).join('\n')).not.toContain('.json');
  });
});
