import type { WebsiteCompiledContent } from './adapter';

export interface WebsiteGeneratedModules {
  routes: string;
  pages: string;
  navigation: string;
  media: string;
  index: string;
}

const generatedHeader = [
  '/*',
  ' * This file is generated by Commonloom. Do not edit.',
  ' * Update Markdown copy and page-group manifests, then run npm run content:generate.',
  ' */',
  '',
].join('\n');

export function emitWebsiteGeneratedModules(
  records: WebsiteCompiledContent,
): WebsiteGeneratedModules {
  return {
    routes: emitRoutes(records),
    pages: emitPages(records),
    navigation: emitNavigation(records),
    media: emitMedia(records),
    index: emitIndex(),
  };
}

function emitRoutes(records: WebsiteCompiledContent): string {
  return [
    generatedHeader,
    "import type { WebsiteRoute } from '../routes';",
    '',
    `export const websiteRoutesGenerated = ${stableStringify(records.routes)} as const satisfies readonly WebsiteRoute[];`,
    '',
  ].join('\n');
}

function emitPages(records: WebsiteCompiledContent): string {
  return [
    generatedHeader,
    "import type { WebsiteGeneratedPage } from '../pipeline/website/adapter';",
    '',
    `export const websitePagesGenerated = ${stableStringify(records.pages)} as const satisfies readonly WebsiteGeneratedPage[];`,
    '',
  ].join('\n');
}

function emitNavigation(records: WebsiteCompiledContent): string {
  return [
    generatedHeader,
    "import type { WebsiteGeneratedNavigationGroup } from '../pipeline/website/adapter';",
    '',
    `export const websiteNavigationGenerated = ${stableStringify(records.navigation)} as const satisfies readonly WebsiteGeneratedNavigationGroup[];`,
    '',
  ].join('\n');
}

function emitMedia(records: WebsiteCompiledContent): string {
  return [
    generatedHeader,
    "import type { WebsiteGeneratedMediaRecord } from '../pipeline/website/adapter';",
    '',
    `export const websiteMediaGenerated = ${stableStringify(records.media)} as const satisfies readonly WebsiteGeneratedMediaRecord[];`,
    '',
  ].join('\n');
}

function emitIndex(): string {
  return [
    generatedHeader,
    "export * from './routes.generated';",
    "export * from './pages.generated';",
    "export * from './navigation.generated';",
    "export * from './media.generated';",
    '',
  ].join('\n');
}

function stableStringify(value: unknown): string {
  return JSON.stringify(sortValue(value), null, 2);
}

function sortValue(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(sortValue);
  }

  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, child]) => [key, sortValue(child)]),
    );
  }

  return value;
}
